'use client';
import {useState,useRef,useEffect} from 'react';
import {BookOpen,Layers,Upload,FileText,Check,ChevronLeft,ChevronRight,RotateCcw,GraduationCap,ShieldCheck,Plus,ArrowUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {generateCards,makeQuiz,demo,type Slide,type Card} from '@/lib/study';
import {extractFile} from '@/lib/extract';

export default function Home(){
 const [slides,setSlides]=useState<Slide[]>([]),[cards,setCards]=useState<Card[]>([]),[name,setName]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[drag,setDrag]=useState(false),[tab,setTab]=useState('flashcards'),[index,setIndex]=useState(0),[flipped,setFlipped]=useState(false),[known,setKnown]=useState<number[]>([]),[quiz,setQuiz]=useState<ReturnType<typeof makeQuiz>>([]),[qi,setQi]=useState(0),[responses,setResponses]=useState<string[]>([]),[typed,setTyped]=useState(''),[done,setDone]=useState(false),[paste,setPaste]=useState(''),[showPaste,setShowPaste]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null);const card=cards[index];const current=quiz[qi];
 const correct=(a:string,b:string)=>a.trim().toLowerCase().replace(/[.!?]+$/,'')===b.trim().toLowerCase().replace(/[.!?]+$/,'');
 function load(data:Slide[],title:string){const next=generateCards(data);if(!next.length)throw new Error('No usable study statements were found. Try a text-based PDF, or paste complete notes below. Scanned images and diagrams are not read.');setSlides(data);setCards(next);setName(title);setIndex(0);setFlipped(false);setKnown([]);setQuiz(makeQuiz(next));setQi(0);setResponses([]);setDone(false);setTyped('');setTab('flashcards');setError('');}
 async function upload(file?:File){if(!file||busy)return;setBusy(true);setError('');setStatus('Opening your lecture…');try{const data=await extractFile(file,setStatus);load(data,file.name);}catch(e){setError(e instanceof Error?e.message:'We couldn’t read this file. Try exporting it as a text-based PDF.');}finally{setBusy(false);setStatus('');if(fileRef.current)fileRef.current.value='';}}
 function move(n:number){setIndex(i=>(i+n+cards.length)%cards.length);setFlipped(false);}
 function restart(){setQuiz(makeQuiz(cards));setQi(0);setResponses([]);setTyped('');setDone(false);}
 function answer(value:string){if(responses.length>qi||!value.trim())return;setResponses(r=>[...r,value.trim()]);}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'generate_study_set_from_text',description:'Create flashcards and a quiz from supplied lecture text and display the study set. Replaces the current session study set.',inputSchema:{type:'object',properties:{text:{type:'string'},title:{type:'string'}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:any)=>{if(typeof input?.text!=='string'||input.text.length<30||input.text.length>500000)throw new Error('Provide between 30 and 500000 characters of lecture text.');if(input.title!==undefined&&typeof input.title!=='string')throw new Error('Title must be text.');const data=[{number:1,text:input.text}];load(data,input.title||'Lecture notes');return {flashcards:generateCards(data).length,status:'ready'};}},{signal:life.signal})).catch(()=>{});return()=>life.abort();},[]);
 const emptyPages=slides.filter(s=>s.text.trim().length<20).length;
 return <div className="app-shell">
  <header className="topbar"><a className="brand" href="./" aria-label="SlideStudy home"><span className="brand-icon"><Layers size={23}/></span>Slide<span>Study</span></a><div className="top-note"><ShieldCheck size={16}/> Files stay in your browser</div><span className="edition">YOUR STUDY SPACE</span></header>
  <main>
   <div className="page-heading"><div><p className="eyebrow">LESS REREADING. MORE RECALL.</p><h1>Make your lecture stick.</h1><p className="subtitle">Your slides, turned into a study session.</p></div><div className="heading-mark"><GraduationCap size={34}/></div></div>
   <div className="workspace">
    <aside className="upload-panel">
     <div className="section-title"><span className="step">01</span><h2>Your lecture</h2></div>
     <div className={'dropzone '+(drag?'dragging':'')} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void upload(e.dataTransfer.files[0]);}}>
      <div className="upload-icon"><Upload size={26}/></div><h3>{busy?'Reading your slides…':'Drop your slides here'}</h3><p>PDF, PowerPoint (.pptx), or TXT</p><button className="primary" disabled={busy} onClick={()=>fileRef.current?.click()}><Plus size={17}/>{busy?'Processing…':cards.length?'Upload another lecture':'Choose a file'}</button><span className="fine">Up to 20 MB · 250 slides</span><input ref={fileRef} type="file" accept=".pdf,.pptx,.txt" hidden onChange={e=>void upload(e.target.files?.[0])}/>
     </div>
     <div aria-live="polite">{busy&&<p className="status">{status}</p>}</div>{error&&<p className="error" role="alert">{error}</p>}
     <button className="text-button paste-toggle" onClick={()=>setShowPaste(!showPaste)}>{showPaste?'Hide notes input':'Or paste your lecture notes'}</button>
     {showPaste&&<div className="paste-area"><label htmlFor="notes">Lecture notes</label><textarea id="notes" value={paste} maxLength={500000} onChange={e=>setPaste(e.target.value)} placeholder="Paste definitions, explanations, or slide text…"/><button className="primary" disabled={busy||paste.trim().length<30} onClick={()=>{try{load([{number:1,text:paste}],'Pasted lecture notes');}catch(e){setError((e as Error).message);}}}>Make study set</button></div>}
     {cards.length>0&&<div className="file-summary"><span className="file-icon"><FileText size={21}/></span><div><strong>{name}</strong><p>{slides.length} {slides.length===1?'page':'pages'} · {cards.length} flashcards</p></div><Check size={18}/></div>}
     <div className="how-it-works"><p className="eyebrow">A LITTLE ACTIVE RECALL</p><div><span>1</span><p>Bring your lecture slides.</p></div><div><span>2</span><p>Recall the answer before you flip.</p></div><div><span>3</span><p>Test yourself, then revisit the gaps.</p></div></div>
     <div className="processing-note"><BookOpen size={18}/><p>Questions come directly from slide text, using definitions and fill-in-the-blanks. Images and diagrams aren’t read. <strong>This session clears when you reload.</strong></p></div>
    </aside>
    <section className="study-panel" aria-label="Study workspace">
     <div className="study-title"><div className="section-title"><span className="step">02</span><h2>Put it into practice</h2></div><span className="session-tag">{cards.length?'READY TO STUDY':'START WITH A LECTURE'}</span></div>
     <Tabs value={tab} onValueChange={setTab}>
      <TabsList className="study-tabs"><TabsTrigger value="flashcards"><Layers size={17}/> Flashcards {cards.length>0&&<span className="count">{cards.length}</span>}</TabsTrigger><TabsTrigger value="quiz"><GraduationCap size={18}/> Quiz</TabsTrigger><TabsTrigger value="source"><FileText size={17}/> Source</TabsTrigger></TabsList>
      {!cards.length?<div className="empty-state"><div className="sample-top"><span className="eyebrow">A PREVIEW OF YOUR NEXT STUDY SESSION</span><span className="sample-label">SAMPLE CARD</span></div><div className="sample-card"><span className="card-kicker">COMPUTER SCIENCE · ACTIVE RECALL</span><h2>Which data structure follows<br/>last-in, first-out?</h2><div className="preview-bottom"><span>Think it through.</span><span className="tiny-stack"><Layers size={22}/></span></div></div><div className="empty-caption"><h3>A whole lecture. Bite-sized questions.</h3><p>Upload your slides to make a set, or try a short sample.</p><button className="secondary" disabled={busy} onClick={()=>load(demo,'Data structures · sample lecture')}>Try a sample lecture <ArrowUpRight size={16}/></button></div></div>:<>
      <TabsContent value="flashcards">
       <div className="study-meta"><span>CARD <strong>{index+1}</strong> / {cards.length}</span><span>{known.length} recalled</span></div><Progress value={known.length/cards.length*100} aria-label="Cards recalled"/>
       <button className={'flashcard '+(flipped?'flipped':'')} onClick={()=>setFlipped(!flipped)} aria-label={flipped?'Showing answer. Click to show question.':'Show answer'}><span className="card-kicker">{flipped?'THE ANSWER':card.kind==='definition'?'NAME THE CONCEPT':'FILL IN THE BLANK'}</span><span className="card-text">{flipped?card.answer:card.question}</span>{flipped&&<span className="source-quote">“{card.source}”</span>}<span className="card-foot"><span>Slide {card.slide}</span><span>{flipped?'Click to see question':'Click to reveal answer'} <RotateCcw size={14}/></span></span></button>
       <div className="card-controls"><button className="icon-button" aria-label="Previous card" onClick={()=>move(-1)}><ChevronLeft/></button><button className={known.includes(card.id)?'secondary recalled':'secondary'} onClick={()=>{setKnown(k=>k.includes(card.id)?k.filter(id=>id!==card.id):[...k,card.id]);}}><Check size={17}/>{known.includes(card.id)?'Recalled':'Mark as recalled'}</button><button className="icon-button" aria-label="Next card" onClick={()=>move(1)}><ChevronRight/></button></div><p className="hint">Say your answer out loud before revealing it.</p>
      </TabsContent>
      <TabsContent value="quiz">
       {done?<div className="results"><span className="eyebrow">SESSION COMPLETE</span><h2>{responses.filter((a,i)=>correct(a,quiz[i].card.answer)).length}<span> / {quiz.length}</span></h2><p>Here’s what to take into your next review.</p><button className="primary" onClick={restart}><RotateCcw size={16}/>Try a new quiz</button><div className="review-list">{quiz.map((q,i)=><article key={q.card.id}><span className={correct(responses[i]||'',q.card.answer)?'result-badge good':'result-badge'}>{correct(responses[i]||'',q.card.answer)?'Correct':'Review'}</span><h3>{q.card.question}</h3><p>Your answer: {responses[i]}</p><strong>Answer: {q.card.answer}</strong><details><summary>Why? · Slide {q.card.slide}</summary><p>{q.card.source}</p></details></article>)}</div></div>:current&&<div className="quiz-body"><div className="study-meta"><span>QUESTION <strong>{qi+1}</strong> / {quiz.length}</span><span>{responses.filter((a,i)=>correct(a,quiz[i].card.answer)).length} correct</span></div><Progress value={responses.length/quiz.length*100} aria-label="Quiz progress"/><h3 className="quiz-question">{current.card.question}</h3>{current.options.length?<div className="options">{current.options.map((option,i)=>{const checked=responses.length>qi;const isCorrect=correct(option,current.card.answer);return <button key={option} disabled={checked} className={'option '+(checked?(isCorrect?'correct':responses[qi]===option?'wrong':''):'')} onClick={()=>answer(option)}><span>{String.fromCharCode(65+i)}</span>{option}{checked&&isCorrect&&<Check size={18}/>}</button>;})}</div>:<form onSubmit={e=>{e.preventDefault();answer(typed);}}><label htmlFor="answer">Your answer</label><input id="answer" className="answer-input" value={typed} disabled={responses.length>qi} onChange={e=>setTyped(e.target.value)} autoComplete="off"/>{responses.length<=qi&&<button className="primary" disabled={!typed.trim()}>Check answer</button>}</form>}{responses.length>qi&&<div className="answer-feedback" aria-live="polite"><strong>{correct(responses[qi],current.card.answer)?'That’s right.':'The answer is '+current.card.answer+'.'}</strong><p>{current.card.source}</p><span className="fine">From slide {current.card.slide}</span><button className="primary" onClick={()=>{if(qi===quiz.length-1)setDone(true);else{setQi(qi+1);setTyped('');}}}>{qi===quiz.length-1?'See results':'Next question'}</button></div>}</div>}
      </TabsContent>
      <TabsContent value="source"><div className="source-heading"><h3>What your slides say</h3><p>Use the original text to check every generated question.</p></div>{emptyPages>0&&<p className="notice">{emptyPages} page(s) had little or no readable text. Their images and diagrams are not included in the study set.</p>}<div className="source-list">{slides.map(s=><article key={s.number}><span className="eyebrow">SLIDE {s.number}</span><p>{s.text||'No readable text on this slide.'}</p></article>)}</div></TabsContent>
      </>}
     </Tabs>
     <div className="workspace-footer"><span><ShieldCheck size={14}/> No account or API key needed</span><span>Made for focused minds.</span></div>
    </section>
   </div><footer className="page-footer"><span>SlideStudy</span><p>Study from your slides. Check important details against your lecture.</p></footer>
  </main>
 </div>;
}
